spring:
  application.name: chat-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chatdb?useSSL=false&serverTimezone=UTC
    username: root
    password: 1111
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
  redis:
    host: localhost
    port: 6379

jwt:
  secretKey: YXNkZmtsYXNkbGtmamFvaXNldWxzYWtkZmxrc2NjeG5vaWFld2pybGFzamZsd2FldWpsa2FzZG1mbGF3ZXVsa2FzZmFlamZsYWtzZGZhc29pZGZqYWxzZGpmb2Fpd2VqZmxrYXNkamZsa2FzZGpm
  expiration: 3000